### ISSUE TITLE
Feat: 장소 등록 API 수정

### ISSUE THREAD

**Issue by qzzloz** [locavell/locavel-BackEnd#26]
### 💻 작업 내용
- 장소 등록 API를 수정합니다.

### ✅ Todo
- [x] 등록한 장소를 데이터베이스에 저장할 때, 사용자가 입력한 주소가 아닌 정확한 도로명 주소로 저장
- [x] 도로명 주소를 토대로 시, 구 정보도 가져와서 region column에 저장
- [x] 장소 등록 시 이미지 추가
- [x] 이미 등록된 장소일 경우 에러 발생
