### ISSUE TITLE
Feat: 장소 목록 조회 API 구현

### ISSUE THREAD

**Issue by qzzloz** [locavell/locavel-BackEnd#30]
### 💻 작업 내용
- 장소 목록 조회 API를 구현합니다.

### ✅ Todo
- [x] 내 주변 장소 조회
- [x] 스팟 필터 조회 (마커)
- [x] 푸드 필터 조회 (마커)
- [x] 액티비티 필터 조회 (마커)
- [x] 스팟 필터 목록 버튼 조회
- [x] 푸드 필터 목록 버튼 조회
- [x] 액티비티 필터 목록 버튼 조회
